# Site settings
title:          TARS
description:    "Tars0523's blog"
url:            https://github.com/Tars0523

# Author
author:
  name:         jiwoo kim
  email:        tars0523@unist.ac.kr
  url:          https://github.com/Tars0523

# Build settings
markdown:       kramdown
kramdown:
  input: GFM
  math_engine: mathjax
  math_engine_opts:
    preview: false
    
# Assets
sass:
  sass_dir:     _sass
  style:        compressed

# Gems
plugins:
  - jekyll-feed
  - jekyll-paginate
  # - jemoji #Uncomment this to allow emoji in your post

# Permalinks
permalink:      /:year-:month-:day/:title
paginate:       5

# Related posts settings
related_posts_section:
  max_count:        5
  min_common_tags:  2

# Links to social media
social:
  email: tars0523@unist.ac.kr
  github: https://github.com/Tars0523
  twitter: https://github.com/Tars0523
  linkedin: https://github.com/Tars0523
